services:
  postgres:
    image: postgres:16

    container_name: medcore-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medcore
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    container_name: medcore-api
    restart: always
    ports: 
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/medcore
      JWT_SECRET: super-secret-key
      PORT: 3000
    depends_on:
      - postgres

volumes:
  postgres_data: {}